name: 'drug_consumption_prediction'
channels:
  - conda-forge
  - defaults
dependencies:
- altair=4.2.0
- pandas=1.4.3
- numpy=1.23.3
- dataframe_image = 0.1.1
- ipykernel
- ipywidgets
- ipython>=7.15
- vega_datasets
- altair_saver
- selenium<4.3.0
- scikit-learn==1.1.3
- pip
- pip:
  - docopt-ng==0.8.1
  - webdriver-manager
  - jupyter_core
  - jupyter_client
